#! /bin/ksh

#  VERSION : 16.01.96 19:51

Name=`basename $0`
Usage="$Name: Naka-to-DG format conversion
Usage: $Name Naka-file DG-file
       where DG-file is the output filename,
       and Naka-file is the input filename.
"

[ $# -lt 2 ] && { echo "$Usage"; exit; }
[ -r $1 ] || { echo "File $1 is absent\n"; echo "$Usage"; exit; }
rm -f fort.2 > /dev/null
ln -sf $1 fort.1
`dirname $0`/$OBJECTCODE/nk2dg && { mv fort.2 $2; rm -f fort.1; }
