#! /bin/ksh

#  VERSION : 18.01.96 15:14

Name=`basename $0`
Usage="$Name: CARRE-to-DG format conversion
Usage: $Name CARRE-file DG-file \[Field-file\]
       where DG-file is the output filename,
       and CARRE-file and Field-file are the input filenames.
       If the Field-file is not specified, the default field.snn is used.
"

[ $# -lt 2 ] && { echo "$Usage"; exit; }
F='field.snn'; [ -n "$3" ] && F=$3
[ -r $1 ] || { echo "File $1 is absent\n"; echo "$Usage"; exit; }
rm -f fort.2 > /dev/null
ln -sf $1 fort.1
ln -sf $F fort.3
`dirname $0`/$OBJECTCODE/vr2dg && { mv fort.2 $2; rm -f fort.[13]; }
